"""empty message

Revision ID: 300b5a2d231c
Revises: 6dda7506860d
Create Date: 2024-09-28 16:06:06.176197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300b5a2d231c'
down_revision = '6dda7506860d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_username_key', ['username'])

    # ### end Alembic commands ###
