"""empty message

Revision ID: 34444f3b3cfa
Revises: fb0d19392075
Create Date: 2024-10-04 06:37:38.179799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34444f3b3cfa'
down_revision = 'fb0d19392075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
