name: CI
on:
  push:
    tags:
    - '*'
  release:
    types: [published]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-and-build:
    name: Validate Tag and Build
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.validate-tag.outputs.release }}
      build-command: ${{ steps.validate-tag.outputs.build-command }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate Tag
        id: validate-tag
        run: |
          TAG=${GITHUB_REF_NAME}

          if [[ $GITHUB_EVENT_NAME == "release" && $TAG == v[0-9]*\.[0-9]*\.[0-9]* ]]; then
            echo "release=true" >> $GITHUB_OUTPUT
            echo "build-command=npm run build" >> "$GITHUB_OUTPUT"
          elif [[ $GITHUB_EVENT_NAME != "release" ]]; then
            echo "release=false" >> $GITHUB_OUTPUT
            echo "build-command=npm run build:dev" >> "$GITHUB_OUTPUT"
          else
            echo "Release ${TAG} does not comply with the expected format."
            echo "${GITHUB_EVENT_NAME}"
            exit 1
          fi

      - name: Set Output for Build Command
        id: set-output
        run: |
          echo "::set-output name=build-command::$(cat $GITHUB_ENV | grep build-command | cut -d'=' -f2)"

      - name: Log Validation Result
        run: |
          echo "Is Release: ${{ env.release }}"
          echo "Build Command: ${{ env.build-command }}"

  build-and-deploy:
    name: Build and Deploy
    needs: validate-and-build
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "${{ needs.validate-and-build.outputs.release }} --- ${{ needs.validate-and-build.outputs.build-command }}"
